module.exports = {
  apps: [
    {
      name: "absensi-bot",
      script: "./index.js",
      instances: 1,
      exec_mode: "fork",
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      restart_delay: 3000,
      // Chromium plus face verification uses native memory outside V8's heap.
      // Keep a safety restart threshold without restarting during normal load.
      max_memory_restart: "1536M",
      node_args: "--max-old-space-size=768",
      env: {
        NODE_ENV: "production",
        FACE_WORKER_COUNT: "1",
        FACE_QUEUE_LIMIT: "100",
        FACE_TIMEOUT_MS: "60000",
        FACE_SLOW_LOG_MS: "10000",
        FACE_REFERENCE_CACHE_LIMIT: "500",
        FACE_TINY_INPUT_SIZE: "320",
        FACE_TINY_SCORE_THRESHOLD: "0.45",
        NOTIFICATION_CONCURRENCY: "2",
        NOTIFICATION_QUEUE_LIMIT: "50",
        WA_SEND_MAX_RETRIES: "3",
        WA_SEND_RETRY_BASE_DELAY_MS: "5000",
        WA_SEND_RETRY_MAX_DELAY_MS: "60000",
        WA_SEND_RETRY_JITTER_RATIO: "0.35",
        LID_LOOKUP_TIMEOUT_MS: "4000",
        WA_RECIPIENT_LOOKUP_TIMEOUT_MS: "5000",
        WA_CLIENT_ID: "absensi-bot",
        WA_AUTH_DATA_PATH: "./.wwebjs_auth",
        WA_AUTH_TIMEOUT_MS: "60000",
        WA_QR_MAX_RETRIES: "0",
        WA_TAKEOVER_ON_CONFLICT: "false",
        WA_TAKEOVER_TIMEOUT_MS: "0",
        WA_DEVICE_NAME: "Ruang Hadir",
        WA_BROWSER_NAME: "Chrome",
        WA_HEADLESS: "true",
      },
    },
  ],
};
