module.exports = {
  apps: [
    {
      name: "absensi-bot",
      script: "./index.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 3000,
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=768",
      env: {
        NODE_ENV: "production",
        FACE_WORKER_COUNT: "2",
        FACE_QUEUE_LIMIT: "100",
        FACE_TIMEOUT_MS: "60000",
        NOTIFICATION_CONCURRENCY: "2",
        NOTIFICATION_QUEUE_LIMIT: "200",
        LID_LOOKUP_TIMEOUT_MS: "1500",
        WA_CLIENT_ID: "absensi-bot",
        WA_AUTH_DATA_PATH: "./.wwebjs_auth",
        WA_AUTH_TIMEOUT_MS: "60000",
        WA_QR_MAX_RETRIES: "0",
        WA_TAKEOVER_ON_CONFLICT: "false",
        WA_TAKEOVER_TIMEOUT_MS: "0",
        WA_DEVICE_NAME: "Ruang Hadir",
        WA_BROWSER_NAME: "Chrome",
        WA_HEADLESS: "true",
      },
    },
  ],
};
